### ISSUE TITLE
COMException: Exception from HRESULT: 0x80071BFD

### ISSUE THREAD

**Issue by PeterJD** [dzimchuk/book-fast-service-fabric#17]
Hi dzimchuk

Attempted to run application but below error occurred, any idea of what I can do to correct the issue
Kind regards
Peter
![BookFast Facility Program Main](https://user-images.githubusercontent.com/5926879/56884299-3da36080-6a61-11e9-8976-7b80a821ac70.jpg)

System.InvalidOperationException
  HResult=0x80131509
  Message=The operation is invalid.
  Source=System.Fabric
  StackTrace:
   at System.Fabric.Interop.Utility.WrapNativeSyncInvoke[TResult](Func`1 func, String functionTag, String functionArgs)
   at System.Fabric.Interop.Utility.RunInMTA[TResult](Func`1 func)
   at Microsoft.Diagnostics.EventFlow.ServiceFabric.ServiceFabricHealthReporter..ctor(String entityIdentifier)
   at Microsoft.Diagnostics.EventFlow.ServiceFabric.ServiceFabricDiagnosticPipelineFactory.CreatePipeline(String healthEntityName, String configurationFileName, String configurationPackageName)
   at BookFast.Facility.Program.Main() in C:\book-fast-service-fabric-CMS\BookFast.Facility\Program.cs:line 17

Inner Exception 1:
COMException: Exception from HRESULT: 0x80071BFD

**Comment by sridhargandham** [comment]
I'm also facing same problem, did you get the solution?
